name: Notify on README change

on:
  push:
    paths:
      - 'readme.md'

jobs:
  send_mail:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: README.md has been updated
          to: ernstcd@example.com
          body: README.md was updated in this commit: ${{github.sha}}. Please review the changes.
